# Generated by Django 4.2.30 on 2026-05-14 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-release_date', 'title'], 'verbose_name': 'film', 'verbose_name_plural': 'films'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['name'], 'verbose_name': 'studio', 'verbose_name_plural': 'studios'},
        ),
        migrations.AlterField(
            model_name='film',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must contain only lowercase letters, numbers and hyphens.', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['release_date'], name='films_film_release_ae2462_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['title'], name='films_film_title_72d7db_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['slug'], name='films_genre_slug_c42e24_idx'),
        ),
        migrations.AddIndex(
            model_name='studio',
            index=models.Index(fields=['name'], name='films_studi_name_957a14_idx'),
        ),
    ]
